import type { CaseStudy } from './types';

export const caseStudies: CaseStudy[] = [
  {
    id: 'inovytec-ventway-sparrow',
    title: 'Inovytec Ventway Sparrow — FDA 510(k) with Parasoft C/C++test',
    specialty: 'Respiratory / Emergency Ventilators',
    pathway: '510(k)',
    sourceUrl: 'https://www.parasoft.com/resources/case-studies/inovytec-achieves-fda-certification-with-customized-static-code-analysis-solution/',
    sourceLabel: 'Verified Parasoft Case Study',
    beforeESL: [
      'Embedded ventilator software needed FDA 510(k) compliance with no static analysis baseline',
      'No customized rule set mapped to FDA 510(k) certification requirements',
      'Code quality issues hidden across the embedded C/C++ codebase',
      'No automated verification workflow before software releases',
    ],
    afterESL: [
      'ESL deployed Parasoft C/C++test with FDA 510(k)-customized static analysis rules',
      'Every Ventway Sparrow release now runs Parasoft static analysis configured to FDA regulation definitions',
      '100% of FDA 510(k) certification rules and guidelines passed',
      'Direct support from ESL (Dani Liezrowice) as Parasoft\u2019s Israeli distributor \u2014 immediate response on any issue',
      'Code quality improvements achieved alongside full compliance verification',
    ],
    result: 'FDA 510(k) certification achieved. Parasoft C/C++test became the testing solution of choice at Inovytec, with ESL providing ongoing local support as Parasoft\u2019s authorized Israeli distributor.',
  },
  {
    id: 'cardiac-imaging',
    title: 'AI-Based Cardiac Imaging Device',
    specialty: 'Cardiology / Radiology',
    pathway: '510(k)',
    beforeESL: [
      'Unknown open-source components in the build',
      'No SBOM produced for FDA submission',
      '340 unresolved static analysis findings (MISRA C:2023)',
      'No structural coverage evidence',
      'Disconnected test reports across 3 tools',
    ],
    afterESL: [
      'CycloneDX SBOM with VEX decisions generated by SBOMator\u2122',
      'All CVEs triaged: 12 remediated, 8 documented with compensating controls',
      '12 real defects fixed by ESL engineers; 328 false positives filtered',
      '87% branch coverage with risk-based justification for uncovered code',
      'Full traceability in Polarion ALM via Parasoft Test Tool Suite Connector',
    ],
    result: 'FDA 510(k) clearance achieved with zero software evidence deficiencies flagged in the substantive review.',
  },
  {
    id: 'embedded-firmware',
    title: 'Embedded Firmware AI Medical Device (Binary-Only)',
    specialty: 'Anesthesiology',
    pathway: 'PMA',
    beforeESL: [
      'Firmware available only as compiled binary \u2014 no full source tree',
      'No component inventory for the supply chain',
      'No coverage data from cross-compiled target',
      'No ALM traceability \u2014 requirements in spreadsheets',
    ],
    afterESL: [
      'SBOMator\u2122 extracted SBOM from firmware binary \u2014 no source required',
      '14 CVEs correlated; 3 critical vulnerabilities patched in upstream components',
      'On-target testing: module-by-module instrumentation, results merged',
      'Requirements, risks, tests, and results linked in Polarion ALM',
      'MC/DC coverage evidence assembled for Class C software',
    ],
    result: 'PMA submission included complete software evidence package. SBOMator\u2019s binary-only capability was critical \u2014 no other tool could produce the SBOM from firmware alone.',
  },
  {
    id: 'cloud-saas',
    title: 'Cloud-Based AI Diagnostic SaaS',
    specialty: 'Radiology',
    pathway: 'De Novo',
    beforeESL: [
      'Containerized deployment with 47 dependencies \u2014 no inventory',
      'No \u00a7524B cybersecurity evidence prepared',
      'Static analysis backlog of 180 findings (CERT C/C++, CWE)',
      'Unit tests covered only 34% of statements \u2014 no branch coverage',
    ],
    afterESL: [
      'Container SBOM generated by SBOMator\u2122 (CycloneDX + VEX)',
      'Section 524B evidence mapping: premarket + postmarket monitoring plan',
      'ESL fixed 41 real defects; remaining 139 triaged as false positives or accepted deviations',
      '92% branch coverage with documented justification for uncovered error-handling paths',
      'CI pipeline integrated with controlled baselines and release gates',
    ],
    result: 'De Novo granted. FDA reviewer specifically noted the cybersecurity evidence package as comprehensive and well-organized.',
  },
  {
    id: 'multi-target',
    title: 'Multi-Platform AI Medical Software (Desktop + Mobile + Cloud)',
    specialty: 'Ophthalmology',
    pathway: '510(k)',
    beforeESL: [
      '3 platforms (C++ desktop, C# server, Java mobile) \u2014 no unified evidence',
      'No consistent coding standard enforcement across platforms',
      'Coverage measured differently on each platform \u2014 not comparable',
      'No traceability across the multi-platform architecture',
    ],
    afterESL: [
      'SBOMator\u2122 produced SBOMs for all 3 platforms from source, packages, and containers',
      'Parasoft C/C++test for C++, Parasoft dotTEST for C#, Parasoft Jtest for Java',
      'Unified coverage methodology: branch coverage for all Class B components',
      'Cross-platform traceability matrix in Polarion ALM connecting all platforms',
    ],
    result: '510(k) cleared. ESL\u2019s technology-independent execution was key \u2014 one team, one evidence standard, three platforms.',
  },
];

export function getCaseStudyById(id: string): CaseStudy | undefined {
  return caseStudies.find(cs => cs.id === id);
}
